// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeH8E9uPXaBoqeTJXrcxVvR3YODjbIhBU',
    appId: '1:129082443739:web:9b6b2b1b0badb339df49fe',
    messagingSenderId: '129082443739',
    projectId: 'covidprotocol-6751a',
    authDomain: 'covidprotocol-6751a.firebaseapp.com',
    storageBucket: 'covidprotocol-6751a.appspot.com',
    measurementId: 'G-35GLS7EE88',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-gZdCrgN9KzSjN1h5hnuAlyO1_Bcvs_c',
    appId: '1:129082443739:android:43032672d838972bdf49fe',
    messagingSenderId: '129082443739',
    projectId: 'covidprotocol-6751a',
    storageBucket: 'covidprotocol-6751a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC__GOBOQtqHyJP6tU3A3ikMtCa7AMmTzg',
    appId: '1:129082443739:ios:559d966bc1d96b35df49fe',
    messagingSenderId: '129082443739',
    projectId: 'covidprotocol-6751a',
    storageBucket: 'covidprotocol-6751a.appspot.com',
    iosBundleId: 'com.example.miniProject2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC__GOBOQtqHyJP6tU3A3ikMtCa7AMmTzg',
    appId: '1:129082443739:ios:f10c9723092cd8a5df49fe',
    messagingSenderId: '129082443739',
    projectId: 'covidprotocol-6751a',
    storageBucket: 'covidprotocol-6751a.appspot.com',
    iosBundleId: 'com.example.miniProject2.RunnerTests',
  );
}
